export const base = [
  {
    name: "Perła",
    type: "Pils",
    alc: "6.0%",
    ext: "12.2%",
    ibu: "",
    hop: "lubleski",
    prod: "Perła - browary lubelskie S.A.",
    country: "Polska",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSdp5GpEKUkJMz7Xhz8K3WTewCm5IZWPrLglw&usqp=CAU",
    description: "Fajny opisik blebl lblblblsad sdldsl lslsl adas asdas asa aasas as a aw a  ssssass asd as d asd as  asddddddddd assssssssssssssssss asssssssssss",
  },
  {
    name: "Tyskie",
    type: "Pils",
    alc: "6.0%",
    ext: "12.2%",
    ibu: "",
    hop: "słabiutki",
    prod: "nędzny",
    country: "Polska",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Butelka_Tyskie_bez_cienia.png/162px-Butelka_Tyskie_bez_cienia.png",
    description: "Tyskie raczej piwko nie najlepsze",
  },
  {
    name: "Harnaś - napój bogów",
    type: "Pils",
    alc: "6.0%",
    ext: "12.2%",
    ibu: "",
    hop: "słabiutki",
    prod: "nędzny",
    country: "Polska",
    photo: "",
    description: "Harnaś - sam mjut",
  },

]